### ISSUE TITLE
ModuleNotFoundError: No module named 'translate_po.utilities'

### ISSUE THREAD

**Issue by rffontenelle** [zcribe/translate-po#2]
```
>>> from translate_po.main import run
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rffontenelle/.local/lib/python3.8/site-packages/translate_po/main.py", line 6, in <module>
    from .utilities.constants import UNTRANSLATED_PATH, TRANSLATED_PATH, LANGUAGE_SOURCE, LANGUAGE_DESTINATION
ModuleNotFoundError: No module named 'translate_po.utilities'
```

translate-po 1.0.4 doesn't seem to have utilities.py. I see only the following:

```
$ pip show -f translate-po
Name: translate-po
 (...)
Files:
  ../../../bin/sample
  translate_po-1.0.4.dist-info/INSTALLER
  translate_po-1.0.4.dist-info/LICENSE
  translate_po-1.0.4.dist-info/METADATA
  translate_po-1.0.4.dist-info/RECORD
  translate_po-1.0.4.dist-info/WHEEL
  translate_po-1.0.4.dist-info/entry_points.txt
  translate_po-1.0.4.dist-info/top_level.txt
  translate_po/__init__.py
  translate_po/__pycache__/__init__.cpython-38.pyc
  translate_po/__pycache__/main.cpython-38.pyc
  translate_po/main.py
```

**Comment by zcribe** [comment]
Fixed fd82f488f9c54991d4c5674158b86e1f917a47a2
